### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by svtdoug** [mastersign/Mastersign.WinMan#24]
Installed WinMan - run winman.exe, cmd window pops up for fraction of a second then goes away, no GUI displayed.  does not seem to run.  I have .Net framework 4.8 installed.  Win 10.  Also running as Administrator.  
Never mind.  I was running winman.exe.  Tried winmangui.exe and I get the gui.

**Comment by mastersign** [comment]
As the README describes under point 4 of the _Quick Introduction_, the `WinManGui.exe` contains the graphical user interface. The `winman.exe` is a command line tool for applying or killing window layouts with a Windows shortcut or from shell scripts (CMD/PowerShell).

So, to see the GUI you need to run `WinManGui.exe`. I think I can improve the README to make it more clear, that `WinManGui.exe` is the main executable.

**Comment by svtdoug** [comment]
Thank you Tobias.  Shortly after posting, I figure that out and edited the entry – have to run WinManGui.exe to get the GUI.  

 

I have it running, and what I am trying to do is reset my open windows, but am not having any luck.  I run 3 monitors on a Radeon RX580 video card.  Monitor 1 is a 24” ASUS on the left side using display port, monitor 2 is same on right side using display port, and monitor 3 is a 45” 4K Toshiba Fire TV in the center position on an HDMI cable.  I turn off these monitors when I am not at my desk.  When I return, turn on the monitors, all the apps which were on the center Fire TV have repositioned to the left monitor.  Very maddening.  I am trying to use your app to reset the apps to their original positions on the center Fire TV monitor.  I have Saved the positions as my default positions, but when I return to find the apps all crammed into Monitor 1, clicking on Apply, does not reposition them.  What am I missing?   I guess I need a manual on how your application works.

 

Thanks much!

 

Doug

NN7D

**Comment by mastersign** [comment]
I will see if I find the time to write a more detailled documentation during the next couple of days.

A precondition for solving your problem with WinMan is, that you have created a screen configuration pattern for the situation where all monitors are active, a window pattern for every window you trying to move (the title string must be specific enough to savely identify the window, but generic enough to allow for variations in the title - this accomplished by using wildcards `*`), and a layout with all window patterns and their target positions connected to the screen configuration pattern.

**Comment by mastersign** [comment]
I will close this issue, because the problem with the GUI not starting is resolved. I will create another issue to track the documentation.

**Comment by svtdoug** [comment]
Tobias,

 

Thanks for your help.  Ok, I see that there are many steps to accomplish what I am trying to do.  I was looking for something simple (aren’t we all 😊) where you could press “Save Layout”, and all the windows apps are saved, and after Windows has thoroughly messed up the arrangement, press “Restore Layout” and all the windows would be moved back to their saved positions.   Is this possible?  

 

Ok, I am trying to work with the Window Patterns – I have been able to create Window Patterns for some of my windows, but several throw an error – Unhanded exception has occurred in your application.  Access Denied.   I’ve attached the error text.   That particular app is a ham radio logging software – Log4OM and its associated windows.  I also get this error when trying to create new window pattern with task manager.   Ah, ran WinManGUI as administrator and that got around error.  

 

Now on the Layout screen.  I have no clue how to proceed.  Am I trying to Record Position?  I figured the position was recorded in Window Patterns.   After fiddling with this for a while I was able to use the New Window Action button and get a list of the apps from the Window Pattern and click Record Position and it placed the layouts on the GUI.  Not sure what the Restore and Activate checkboxes are for?  

 

Ok, I am going to turn off my monitors, and try to restore this after app jumble.  

 

Hmmm.  Windows jumbled, opened WinManGUI – seems like to have to select each windows action (app name in the list) and click Apply Window Action.  Maybe I missed it, but it would be helpful if there was a restore all Windows feature.  

 

Anyway, I hope this might be helpful.  BTW, long time software developer here using Delphi and MySQL, among other tools.  

 

Thanks again!

 

Doug

NN7D





 

 

 

 

 

and I select one of my open apps in the upper section with all the apps listed, then I click on New Window Pattern and I get an error -

**Comment by mastersign** [comment]
Hi Doug, please do not add further questions to this issue #24, not related to the original topic "Won't run". If you have other technical questions, feel free to open additional issues.

Regarding your struggle with the usablility of the WinManGUI: Currently, I can only say the UI was implemented with the goal of least effort on my side. Therefore, it is not very user friendly. Sorry for that. But I will try to remedy that by documenting the basic process of configuration and usage when I find the time. I will use issue #26 to track that effort.

**Comment by svtdoug** [comment]
Sorry, I was just responding to your email.  

 

Doug
