### ISSUE TITLE
Some apps restore to large width across both monitors.  

### ISSUE THREAD

**Issue by svtdoug** [mastersign/Mastersign.WinMan#28]
Some apps, when restored with Apply Window Action, open up very wide across both monitors and as high as largest monitor height.  Screen shot attached.     
![WinMan_Log4OM](https://user-images.githubusercontent.com/25494404/177212173-d3974dc1-90d6-4eac-b2de-152a30bc20bf.JPG)

Also attached is screen shot of Layout specifics.  One thing I noticed is that when I created the new Window Action for this app, it did not place the layout in the screen mock-up. 
![WinMan_Log4OM_Layout](https://user-images.githubusercontent.com/25494404/177212430-bf5c0ea2-bc6d-4cd6-83b6-1a5affc5b03e.JPG)

Here is the pattern used for this app - 
![WinMan_Log4OM_Pattern](https://user-images.githubusercontent.com/25494404/177213059-2ab076d3-c0db-4063-8001-08e4c4e34999.JPG)

**Comment by mastersign** [comment]
Please make sure, you are using the right units in the position (Percent vs. Pixels).

**Comment by svtdoug** [comment]
Ah, that was it.  Changing the reference to Pixel did the trick.  I wonder why on those particular apps it defaulted to Percent?  Thanks!
